---
home_dir: /var/www # folder with project
app_dir: app # project folder

git_service: gitlab
git_account_name: app_account
git_repository_name: app

private_key: /Users/<%username%>/.ssh/id_rsa

# For environment
node_version: '12'
ansible_distribution_release: 'xenial' #trusty

# Database variables
db_user: app_user
db_name: app_db
db_password: app_password

backup_dir: app_backup

certbot_create_method: standalone
certbot_admin_email: app@gmail.com
certbot_create_stop_services:
  - nginx

domains:
  - { domain: 'api.app.com' }
  - { domain: 'manager.app.com' }
  - { domain: 'app.com' }
