---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    - name: Running NPM build manager
      register: npm_finished_build_manager
      command: npm run manager:build chdir={{home_dir}}/{{app_dir}}

    - name: Running NPM create symlink manager
      when: npm_finished_build_manager.changed
      ignore_errors: True
      command: npm run manager:create:symlink chdir={{home_dir}}/{{app_dir}}
