---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    - name: Running NPM build client
      register: npm_finished_build_client
      command: npm run client:build chdir={{home_dir}}/{{app_dir}}

    - name: Running NPM for create client symlink
      when: npm_finished_build_client.changed
      command: npm run client:create:symlink chdir={{home_dir}}/{{app_dir}}
