---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    - name: Running NPM build manager
      command: npm run manager:build chdir={{home_dir}}/{{app_dir}}/admin-panel
      register: npm_finished_build_manager

    - name: Running NPM create symlink manager
      command: npm run manager:prod:create:symlink chdir={{home_dir}}/{{app_dir}}/admin-panel
      when: npm_finished_build_manager.changed
