---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    # Создаем папку для клиентской части
    - name: Create APP Directory
      file: path={{home_dir}}/{{app_dir}}/client state=directory

    - name: Copy Private Key
      copy: src={{private_key}} dest={{home_dir}} mode=0600

    - name: Git Clone Repo
      git: repo=git@gitlab.com:{{account_client}}/{{repo_client}}.git dest={{home_dir}}/{{app_dir}}/client update=yes force=yes accept_hostkey=yes key_file={{home_dir}}/id_rsa
      register: git_finished
