---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    - name: Running NPM install server
      register: npm_finished_server
      ignore_errors: True
      npm: path={{home_dir}}/{{app_dir}}/server

    - name: Running NPM install manager_dev
      register: npm_finished_manager_dev
      ignore_errors: True
      npm: path={{home_dir}}/{{app_dir}}/manager_dev

    - name: Running NPM install client
      register: npm_finished_client
      ignore_errors: True
      npm: path={{home_dir}}/{{app_dir}}/client
