---
- hosts: all
  become: yes

  vars_files:
    - ../group_vars/global_vars.yml

  tasks:
    - name: Running NPM create symlink client
      command: npm run client:dev:create:symlink chdir={{home_dir}}/{{app_dir}}/admin-panel
